# Site settings
name: Me
title: Leandre Chanzy
description: Just a student with dreams to achieve.
url: https://leandre-chanzy.github.io/
baseurl: ''
email: 
#cover: https://Fastiraz.github.io/img/og.png
logo: https://leandre-chanzy.github.io/img/me.png
#resume: https://Fastiraz.github.io/resume.pdf
social:
  #- title: email
  #  url: mailto:
  - title: LinkedIn
    url: https://www.linkedin.com/in/leandre-chanzy/
  - title: github
    url: https://github.com/leandre-chanzy

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
